version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRESQL_DATABASE_URL: "postgresql://postgres:mysecretpassword@localhost:5432/postgres"
      SOLVER_API_URL: "http://localhost:9000"
      USERNAME: "username"
      PASSWORD: "password"
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    external: true
