services:
  db:
    image: "redis:latest"
    container_name: database
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - puanet

  solver:
    container_name: solver
    image: znittzel/puan-solver-orchestrator:latest
    networks:
      - puanet
    environment:
      RUN_TASKS_LOCALLY: true
    ports:
      - "9000:8000"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: znittzel/puan-db:latest
    environment:
      DATABASE_URL: "redis://database:6379/0"
      SOLVER_API_URL: "http://solver:8000"
    command: >
      /bin/sh -c "poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - puanet
    ports:
      - "8000:8000"
  
networks:
  puanet:
    driver: bridge

volumes:
  db:
