"""Only one parent hash for versions. Parent hash is a foreign key to Version

Revision ID: 72776dfe6e14
Revises: 82d813be314e
Create Date: 2024-10-16 21:09:37.819237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72776dfe6e14'
down_revision: Union[str, None] = '82d813be314e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('parent_hash', sa.String(), nullable=True))
    op.create_foreign_key(None, 'versions', 'versions', ['parent_hash'], ['hash'])
    op.drop_column('versions', 'parent_hashes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('parent_hashes', sa.TEXT(), server_default=sa.text("'{}'::uuid[]"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'versions', type_='foreignkey')
    op.drop_column('versions', 'parent_hash')
    # ### end Alembic commands ###
