"""Add data field to Version table

Revision ID: 82d813be314e
Revises: 94e8ef67e7e2
Create Date: 2024-10-16 17:43:46.361381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d813be314e'
down_revision: Union[str, None] = '94e8ef67e7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'data')
    # ### end Alembic commands ###
